// This is the default configuration for the Popcorn Maker server
// You shouldn't edit this file. Instead, look at the README for
// various configuration options

module.exports = {
  // hostname must match the address in your browser's URL bar
  // If it does not, then Persona sign-in will not work
  // Don't add any trailing slashes, just protocol://hostname[:port]
  "hostname": "http://localhost:8888",

  "OPTIMIZE_JS": false,
  "OPTIMIZE_CSS": false,
  "FORCE_SSL": false,
  "DEBUG": true,

  // PORT is the port that the server will bind to
  // PORT is all caps because all the PaaS providers do it this way

  "PORT": 8888,

  "MAKE_ENDPOINT": "http://localhost:5000",

  // make authentication - private and public keys must be generated by the MakeAPI
  "MAKE_PRIVATEKEY": "",
  "MAKE_PUBLICKEY": "",

  "USER_BAR": "http://localhost:3000",

  "LOGIN_SERVER_URL_WITH_AUTH": "http://popcorn.webmaker.org:password@localhost:3000",

  "AUDIENCE": "https://webmaker.mofostaging.net",

  "GA_ACCOUNT": "",
  "GA_DOMAIN": "",

  "EMBED_HOSTNAME": "",

  "USER_SUBDOMAIN": "",

  "S3_KEY": "",
  "S3_BUCKET": "",
  "S3_SECRET": "",

  "logger" : {
    "format" : "dev"
  },
  "session" : {
    "key": "popcorn.sid",
    "secret": "thisisareallyreallylongsecrettoencryptcookies",
    "cookie": {
      "maxAge": 2419200000,
      "httpOnly": true,
      "secure": false
    },
    "proxy": true
  },
  "staticMiddleware": {
    "maxAge": "0"
  },
  "database": {
    "database": "popcorn",
    "username": null,
    "password": null,
    "options": {
      "logging": false,
      "dialect": "sqlite",
      "storage": "popcorn.sqlite",
      "define": {
        "charset": "utf8",
        "collate": "utf8_general_ci"
      }
    }
  }
};
